name: FDBK
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - audioread=3.0.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - contourpy=1.2.0
  - cycler=0.11.0
  - decorator=5.1.1
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - gettext=0.21.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libflac=1.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - librosa=0.10.2.post1
  - libsndfile=1.2.0
  - libsqlite=3.46.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.10.0
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.31.3
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numba=0.59.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=1.8.0
  - openjpeg=2.3.0
  - openssl=3.0.14
  - packaging=23.2
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=3.10.0
  - pooch=1.7.0
  - pybind11-abi=4
  - pycparser=2.21
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.10.9
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.3.1
  - pytz=2024.1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.32.2
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - setuptools=69.5.1
  - six=1.16.0
  - soxr=0.1.3
  - soxr-python=0.3.7
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.14
  - torchaudio=2.3.1
  - torchvision=0.18.1
  - tornado=6.3.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - wheel=0.43.0
  - x264=1!152.20180806
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - arpeggio==2.0.2
      - clockblocks==0.6.9.post1
      - einops==0.8.0
      - essentia==2.1b6.dev1177
      - expenvelope==0.7.2
      - midiutil==1.2.1
      - pyaudio==0.2.14
      - pymusicxml==0.5.6
      - python-osc==1.8.3
      - tqdm==4.66.4
